### ISSUE TITLE
Make sure deltavrot correction is implemented correctly

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/LocalGroupHaloProps#16]
What's a good test for this?

**Comment by drphilmarshall** [comment]
Some fairly big differences here. First thing to check carefully is the
definitions in VdM compared to ours. Are we comparing apples with apples in
this test?

**Comment by marxwillia** [comment]
In the above comment detailing the discrepancy in the M31 velocities, the deltavrot correction was not being used in the code. Therefore, the first order of business is to integrate the already implemented deltavrot correction and see what the results are.  Note that in the coordinates.py class, there are two possible definitions of deltavrot for M31.  We want to use the delta function definition because the uncertainties are negligible.  The new velocity transformation results are...

M31 velocity:  7.26788043779 +/- 39.6854337707 ,  -105.6368386 +/- 28.2901974661 ,  36.9032768284 +/- 40.304432868
  cf vdM++12: (66+/-27, -76+/-19, 45+/-27) km/s

M31 speed:  126.849851713 +/- 21.9692273813
  cf vdM++12: (110.6 +/- 7.8) km/s

So there is still quite a large discrepancy.

**Comment by drphilmarshall** [comment]
Agreed - but much improved from before. Let's format those print statements
so we can compare better with vdM++12. Probably we should try and reproduce
some of their plots too, as we figure this out.

**Comment by marxwillia** [comment]
The transformation from celestial coordinates to galactic coordinates is now working correctly for RA, DEC --> l, b and for mu_alpha, mu_delta --> mu_l, mu_b:

l,b =  347.15730758, -78.3386152875
  cf XHIP values:  347.15730758 -78.33861529
mu_l,mu_b =  -23.5134553445 -203.483689562
  cf XHIP values: -23.51,-203.48

The method equatorial_to_galactic_proper_motion() takes mu_n and mu_w as parameters, and calculates mu_alpha and mu_delta.  I think these two sets of mu's are actually exactly the same.  The problem was that the method set mu_alpha = -1*mu_w.  Removing the minus sign gives agreement on multiple Hipparcos stars.

**Comment by drphilmarshall** [comment]
Alright, nice work Marc! :-)

**Comment by marxwillia** [comment]
There was a silly bug in the testing in main of coordinates.py.  Also, incorrect units were being used in the testing.  Upon fixing these bugs in the testing, I find that the transformations in coordinates.py are all correctly implemented:

l,b =  [ 347.15730758] -78.3386152875
  cf XHIP values:  347.15730758 -78.33861529
mu_l,mu_b =  -23.5134553445 -203.483689562
  cf XHIP values: -23.51,-203.48
x,y,z =  4.19366817246 -0.95606468303 -20.8407650431
  cf XHIP values: 4.2, -1.0, -20.8
vx,vy,vz =  -24.2656956924 3.09925289521 16.4175661185
  cf XHIP values: -24.3, 3.1, 16.5

However, the testing in triplet.py still shows large discrepancies between the calculated M31 velocities and their true values.  Based on the incorrect units being used in the testing of coordinates.py, I think the first thing to do is make sure that the transformations in coordinates.py expect the units that they are getting from observations.py.

**Comment by marxwillia** [comment]
The last thing that I need to do before conclusively deciding that everything in coordinates.py is implemented correctly is find observed values for the proper motion of the galactic center in equatorial coordinates (mu_RA and mu_DEC).  I have been looking for these values, but cannot find them.  Do you have any good references, @drphilmarshall ?

**Comment by marxwillia** [comment]
Progress!  After my discussion with @yymao , I further checked out an idea about how the galactic coordinate system is defined.  The key part of the definition is that the x axis is the line between the sun and the galactic center.  I think that the direction of rotation when measuring the longitude, l, should be the same regardless of whether one uses heliocentric or galactocentric coordinates.  If this condition is enforced, then objects with negative x coordinates pick up a minus sign in their v_west velocity.  Using this condition, the results of testing triplet.py are...

M31 velocity:  47.1848219676 +/- 39.8135192829 ,  -76.4893550103 +/- 28.0069737046 ,  47.6322931075 +/- 40.1468447922
  cf vdM++12: (66+/-27, -76+/-19, 45+/-27) km/s

I'm not sure about the x velocity, but the y and z velocities look very good!  I still need to verify that the correct measurements were written in the observations.py class.

**Comment by yymao** [comment]
I tried to find a transformation that is consistent with what was used in vdM+12 [1205.6864], and this is what I found that seems most plausible (i.e. it makes sense to me and also reproduces the numbers in vdM+12 very closely) . Using the code below I got `m31_vel_gc = [62.9, -76.3, 49.3]` (don't ask me why the numbers are not exactly the same as in vdM+12).

The trick here is to find the unit vectors of *west* and *north*, and then we don't even need spherical transformation. 

```python
import numpy as np
import math

#from Eq.(1) of vdM+12 [1205.6864]
#in km/s, heliocentric, *some* spherical frame
m31_vel = {'r':-301.0, 'w':-125.2, 'n':-73.8}

#from Sec. 4.1 of vdM+12 [1205.6864]
#in km/s, galactocentric, galactic frame
sun_vel_gc = np.array([11.1, 12.24+239.0, 7.25])

def unit_vec(vec):
    vec = np.asanyarray(vec)
    vec /= math.sqrt((vec*vec).sum())
    return vec

l, b = 121.174405, -21.572936 #M31
l *= math.pi/180.0
b *= math.pi/180.0
los = unit_vec([math.cos(l)*math.cos(b), math.sin(l)*math.cos(b), math.sin(b)])
west = unit_vec(np.cross(los, np.array([0,0,1.0])))
north = unit_vec(np.cross(west, los))

m31_vel_gc = m31_vel['r']*los + m31_vel['w']*west + m31_vel['n']*north
m31_vel_gc += sun_vel_gc
print m31_vel_gc
```

**Comment by marxwillia** [comment]
In order to check Yao's transformations, I should get something equivalent if I calculate mu_north and mu_west from the v_north and v_west values in VdM, and eliminate the deltavrot correction.  The results are very similar, but the x velocity is still not quite right.  

M31 velocity:  51.9113293834 +/- 26.0580875539 ,  -73.7893124011 +/- 19.0528326341 ,  47.299443643 +/- 27.5064556897
  cf vdM++12: (66+/-27, -76+/-19, 45+/-27) km/s

**Comment by yymao** [comment]
@marxwillia can you paste and push the relevant code for transformations you used?

**Comment by marxwillia** [comment]
The heliocentric_equatorial_spherical_to_galactocentric_cartesian() method from coordinates.py does all the work.  The main transformation from spherical to cartesian coordinates is found in...

```def spherical_to_cartesian(RA,DEC,D,mu_west,mu_north,v_r,deltavrot_west, deltavrot_north):

    # Heliocentric Cartesian positions (Mpc):
    delta = DEC*deg2rad
    alpha = RA*deg2rad
    x = D*cos(delta)*cos(alpha)
    y = D*cos(delta)*sin(alpha)
    z = D*sin(delta)

    # Convert mu to v
    v_west = mu_west*muaspyrMpc2kmps*D - 0*deltavrot_west
    for i in range(len(x)):
        if x[i] < 0:
            v_west[i] = -v_west[i]
    v_north = mu_north*muaspyrMpc2kmps*D - 0*deltavrot_north
    print 'v_west: ',mean(v_west)
    print 'v_north: ',mean(v_north)

    vx = v_r*cos(delta)*cos(alpha) - v_west*sin(alpha) - v_north*sin(delta)*cos(alpha)
    vy = v_r*cos(delta)*sin(alpha) + v_west*cos(alpha) - v_north*sin(delta)*sin(alpha)
    vz = v_r*sin(delta) + v_north*cos(delta)
    return x,y,z,vx,vy,vz
```

**Comment by yymao** [comment]
So this actually looks OK. I believe the *west* direction in cdM+12 *is* defined in the opposite direction as what we thought, so you can just do `v_west *= -1` instead of the for loop there. 

And if you call this function with `RA=l` and `DEC=b` you should get the numbers that I got. (Check if it is the case.)

**Comment by marxwillia** [comment]
When using the individual methods in coordinates.py, I recreate Yao's numbers.  When using the triplet.py test, the X and Z velocities are off by a little.  I found that the reason for this is that the coordinates.py code does not actually ever correct for the sun's velocity relative to the LSR in the X or Z directions. After adding this correction into the code, I recreate Yao's numbers exactly:

M31 velocity:  62.936823182 +/- 39.713350287 ,  -76.2073674742 +/- 28.1232257102 ,  49.0378816359 +/- 40.2039095174
  cf vdM++12: (66+/-27, -76+/-19, 45+/-27) km/s

This was without working backwards from VdM's listed v_west and v_north, which is extremely important because these values are not known to the same degree of certainty for M33.  I can now recreate VdM's velocity numbers using only observables, and the deltavrot correction.  I believe this issue has now been fully resolved.

**Comment by drphilmarshall** [comment]
Excellent! Well done Marc. When we meet later today (2:15pm!) let's look through the systematic error list in #46, and start making blinded mass measurements.
