### ISSUE TITLE
Reading in halos and evaluating likelihood

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/LocalGroupHaloProps#31]
* [x] Read in Consuelo halos
* [x] Pickle Triplet
* [x] Evaluate their likelihoods
* [x] Plot, informatively

Have fun! :-)

**Comment by drphilmarshall** [comment]
Good call. Not sure where the read_from_file method should be, you decide.
We can always refactor later, of course :-)

**Comment by marxwillia** [comment]
I don't actually think that a Triplet object is the best way to store the simulation data read in from the Consuelo files.  Each Triplet object has three Halo objects: T.M31, T.MW, T.M33.  The M31 and M33 Halo objects don't have fields for position or velocity.  Furthermore, if the Consuelo data is preprocessed so that it has the form MW_D, MW_vr, MW_vt, M33_D, M33_vr, M33_vt, then I don't envision doing anything with this data other than evaluating its likelihood and plotting it.  Therefore, instead I think we should have a L.sim_points field in the Likelihood object.  There can be a method to read in from a file, with an option to pickle the resulting (n_points, 6) numpy array.

**Comment by drphilmarshall** [comment]
Interesting proposal. Separating out the data "munging" makes a lot of
sense.  Before you implement, though, lets think: the code is currently
designed to enable operations on lists of halos, all at the same time. The
halo objects are ways to  structure data in a way that makes logical sense.
By defining a sim_points method, would we be abandoning this structure just
when the calculation gets interesting? I'm a little worried that when we
come to try and make plots and calculations about the weighted halos after
we've applied the likelihood, we'll have to do more repackaging etc. Before
we go down this road, maybe we should take a long hard look at what can  be
done to upgrade the Halo and Triplet objects so that they remain useful
data structures?

**Comment by marxwillia** [comment]
I completely agree with your above points about the possible negative effects of defining a sim_points method.  Upon further consideration, I've realized that we can in fact store the simulation data in a Triplet object.  The only downside is that certain halo fields, like H.DEC and H.RA, are filled with meaningless data because the simulation does not measure those quantities.  However, I believe it is safe to ignore that, and it will be the user's responsibility to know whether he is using a simulation Triplet object or an actual observation Triplet object.  We can go over this in more detail in person.

**Comment by drphilmarshall** [comment]
Ah, OK! I think the right thing to do is to initialize halo.ra and halo.dec
to None, and then test using "is None" if you want to make safe code. I
think it will work out - when doing the halo smapling using the
pre-computed likelihood, the ra and dec fields will never be used.
