### ISSUE TITLE
Implement Timing Argument

### ISSUE THREAD

**Issue by marxwillia** [drphilmarshall/LocalGroupHaloProps#36]
This is already implemented in code in the attic.  It needs to be put in the appropriate class.

**Comment by marxwillia** [comment]
In Triplet class we need a method called compute_timing_mass that implements the radial timing argument from Li and White 2008 (that Gonzalez et al used).  This code is in the attic.

**Comment by marxwillia** [comment]
Added a Triplet.compute_timing_masses method.  Initial distribution is lower than what is recorded in the Li & White paper:  centered on 4e12 rather than 5e12 when applied to the true data.  When reading from the simulations, we might also want to make a plot of timing argument mass vs actual mass of the MW-M31 pairs.  @drphilmarshall would it be okay for me to make this plot and look at the unblinded results?  It would give me the distribution of the MW-M31 combined mass in the simulations.

**Comment by drphilmarshall** [comment]
What do you think? The combined MW+M31 mass is a key quantity for us, so
does need to be kept blinded while we are still fixing systematics (like
deltavrot, isolation criteria etc). The problem with plotting the prior
halos (not the weighted, posterior ones) is that they depend on the
isolation criteria we are using, which is one of our systematics... I'd say
make plots with axes offset by the means for now. Or convince me otherwise!
:-)

**Comment by marxwillia** [comment]
Triplet.blind() should return at least two random offsets.  One for all masses, and an additional offset for the timing mass true ratio. This will allow us to compare the ratios from different sets of assumptions (systematics) without learning the true masses, or accidentally learning our blind offset.
