### ISSUE TITLE
Triplet.calculate_N95

### ISSUE THREAD

**Issue by marxwillia** [drphilmarshall/LocalGroupHaloProps#44]
The number of triplets that contribute to 95% of the importance.  Find the normalized importance weights of all the triplets, sort them, and count until .95.

**Comment by marxwillia** [comment]
Do #39 first.

**Comment by marxwillia** [comment]
Most of the triplets in the simulation data contribute to the N95 number. For example, when 2000 points are read from the Consuelo catalogs (where a "point" is a LG analog), then around 1964 points contribute to N95.

**Comment by drphilmarshall** [comment]
This might be because the constraints are not yet implemented properly...
This is where a plot of prior PDF for halo properties, with posterior
contours overlaid, will come in handy. If they do not overlap closely, N95
should be small. Don't forget to blind by offsetting to the *prior* mean,
or some random constant similar in value to the prior mean. (If you offset
by both means, the contours will appear to overlap quite closely!)
