### ISSUE TITLE
M31 velocities must agree with Van Der Marel et al (2012)

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/LocalGroupHaloProps#52]
Looks like some sort of bug somewhere: the M31 proper motion _velocities_ don't match vDM2012 equation 1 when `python triplet.py` is run.  This is partly because they are including information from satellite kinematics as well, but still - we should be able to get closer than we are.

One option is to use a (v_W,v_N) vector as _data_, instead of proper motions in micro arcsec / year. Do we have these numbers for M33?

**Comment by drphilmarshall** [comment]
Let's try using the vdM++2012 (v_W,v_N) directly. Its not completely satisfactory, because his v vector already contains D, so we'll be putting the D in twice... but maybe this is not too bad, as its just conservative... Let's see how the vtan of M31 turns out when we go this route. We should see vtan_M31 < 34 km/s.

**Comment by marxwillia** [comment]
We made a very silly mistake while working on this "bug" last time.  The "incorrect" numbers that we were looking at were actually the v_W, v_N numbers for M33.  Above that in the admittedly long readout, were the numbers v_W = 125, v_N = -73 for M31.  So we don't actually have a problem recreating vdM's numbers there.  Our overall speed for M31 is larger than vdM:

Us: |v_M31| = vx*vx + vy*vy + vz*vz = 126 +/- 15
vdM = |v_M31| = vx*vx + vy*vy + vz*vz = 110 +/- 7

This difference actually accounts for our drastically different v_tan numbers since the calculation we make, and that vdM makes is:

v_tan = |v_M31| - |vr_M31|

All of our uncertainties for the velocity numbers are larger than vdM's.  We also do not match the velocity numbers for M33 as well as we match the numbers for M31, but we are still within the uncertainty range:

M33 Velocities: vx = 43.5730159175 +/- 22.3474533654 ,  vy = 89.9341723883 +/- 22.5806161897 ,  vz = 124.392773923 +/- 28.5332102704

compared to the values referenced by vdM++12 in paper 2: vx = 43.1 +/- 21.3, vy = 101.3 +/-23.5, vz = 138 +/- 28.1

I believe that our extra uncertainty is coming from propagating the uncertainty in the celestial proper motions, mu_N, mu_W.  vdM++12 don't do this for M31, instead just using their values for v_N and v_W.  Given that we actually DO reproduce those numbers, I see no reason not to use them as observations.  If similar numbers exist for M33, we can use them, but as for right now I think we should stick to vdM's deltavrot method.

**Comment by drphilmarshall** [comment]
OK, that's some good news! However, let's proceed with caution:

First: don't you mean v_tan = sqrt( |v_M31|^2 - |vr_M31|^2 ) ? And can you
confirm: does our higher M31 speed also come from the larger proper motion
uncertainties? Or is it something else as well?

Second: are you saying that we should use the v_W and v_N values, like
vdM++12 did, or go back to the mu_W and mu_N values? This is an argument
you will also need to make in the latex file of your thesis.

**Comment by marxwillia** [comment]
First:  yes, the v_tan calculation is correctly done as v_tan = sqrt( |v_M31|^2 - |vr_M31|^2 ).  Apparently our higher M31 speed has a cause other than the larger uncertainties.  I am not sure why our speed is incorrect.

Second:  I implemented the code using vdM's v_W and v_N as observed data, and our speed is still about 7km/s too high.  However all of our velocity uncertainties match vdM now, so I think we should keep this change.

**Comment by drphilmarshall** [comment]
OK. The difference in uncertainty between the v's and mu's is troubling.
Perhaps we should contact the authors and ask them. Let's try and track
down the small remaining discrepancy in the M31 vtan, and then discuss,
with @risaw. So: could our M31 speed difference something to do with the
speed and/or distance of the Sun around the galactic center? Does M33's
speed also come out a little high?

**Comment by marxwillia** [comment]
Here's an overview of the velocity transformations:  

Our M31 vx, vy, vz numbers match vdM almost perfectly, but our speed is a little too high.  Our M33 numbers match within the uncertainty range given in vdM's paper, but the vy and vz are about 10 km/s smaller than vdM's.  I am very confident that our transformations are correct.  This afternoon I reimplemented the transformations using the method that Yao referenced in his comment:  https://github.com/drphilmarshall/LocalGroupHaloProps/issues/16#issuecomment-76065531

The numbers that I obtained from our original transformations and the method that Yao used are exactly the same.  The large range in estimates of M31 tangential velocity from the various methods that I have encountered in the literature make me loathe to proclaim vdM's the be all end all of measurements.  Since our vx, vy, vz numbers for both M31 and M33 largely intersect vdM's uncertainty ranges, I think we should proceed assuming that our transformations are correct.  Maybe we should contact vdM about how he computed the total speed of M31?

**Comment by drphilmarshall** [comment]
I agree. I suggest you carry on as you suggest, both with the inferences
and also your detailed thesis write-up. Then, we'll send vdM a copy of the
finished thesis and ask him about the speed as you have written. Of course,
if you get this part of the write-up finished sooner rather than later we
can send him a draft, for comment on this particular issue.

**Comment by rhw** [comment]
Sounds good.
