### ISSUE TITLE
GMM approximation of the prior

### ISSUE THREAD

**Issue by rhw** [drphilmarshall/LocalGroupHaloProps#65]
Try this soon on the Consuelo z=0 snapshots, because it should enable easy exploratation of the isolation criteria.

**Comment by drphilmarshall** [comment]
@marxwillia show us your [notes](http://nbviewer.ipython.org/github/drphilmarshall/LocalGroupHaloProps/blob/master/notes.ipynb), please!  I am excited to see your GMM approximation to the prior PDF `Pr({M},{D,vt,vr} | isolation)`. Looking at the current version (linked above) I guess you may be needing more than one notebook for your notes by now :-)

**Comment by drphilmarshall** [comment]
Acid test (from Slack discussion offline): 

We _must_ get strongly consistent results on the local group mass from just the pairs, comparing the Consuelo sampled prior and the GMM approximation to it.

**Comment by marxwillia** [comment]
Unfortunately it seems that the GMM approximation to the prior does not yield mass posterior distributions that are consistent with the Consuelo prior.  Using only MW-M31 pairs from Consuelo, and then fitting the prior with a GMM to redraw a sample, the log masses are:

M_MW = 11.16 +/- 0.17
M_M31 = 10.85 +/- 0.33
M_LG = 11.35 +/- 0.17

while the results from directly using MW-M31 pairs from Consuelo are:

M_MW = 11.97 +/- 0.40
M_M31 = 11.93 +/- 0.45
M_LG = 12.36 +/- 0.25

**Comment by drphilmarshall** [comment]
Those GMM masses are so small, I suspect a bug. Are you producing plots in
a notebook to visualize the fit? Great if you can paste the nbview URL of
that notebook here so we can comment.

Let's see, but it may well be that the 1 and 2D marginalisations look
consistent, but the N-D inferences are off. The next thing to look at is
how the MassLG accuracy (ie offset) changes as the number of Gaussians in
the mixture is increased.

If this offset persists, it would be an important result, because it would
show that the Next Simplest Possible Thing doesn't work, and would motivate
the kind of method that Iain Murray has been developing with us.

**Comment by marxwillia** [comment]
The offset may actually have been a bug.  It seems to be in agreement now, but I want to do a lot more testing before I am certain that it is correct since this is extremely important.  Also, note my latest comment in #41

**Comment by drphilmarshall** [comment]
Sounds good. Note also the need to double-check the units (see discussion in #59, #41)

**Comment by marxwillia** [comment]
The GMM approximates the prior very well.  I found consistency between the posterior PDFs for halo masses when using the GMM pair prior, and when using the true pair prior.

**Comment by drphilmarshall** [comment]
Great! Very pleased to hear this - it's an important result.
