### ISSUE TITLE
Isolation criteria in latex

### ISSUE THREAD

**Issue by drphilmarshall** [drphilmarshall/LocalGroupHaloProps#67]
Preferably as bullet points, maybe even to enable a line by line comparison with Gonzales.

**Comment by drphilmarshall** [comment]
We'll need to acknowledge the shortcomings of our criteria: the analog groups can have any number of subhalos less massive than M33, etc - which is an opportunity for future work. You might want to postpone this discussion to a section just before the conclusions, where we point out our other to-dos as well.

**Comment by marxwillia** [comment]
I like the idea of having a section before the conclusion to discuss possible areas of improvement or future work.  I will postpone the discussion of the isolation criteria shortcomings to the end.  As of right now, the current isolation criteria are described in the LateX on Overleaf.  I will update the backup copy of the thesis on github because most of the writing before the actual results discussion is now finished.
